# Pre-Commit is a tool that automatically runs hooks such as linters and auto-fixers
# on you codebase before a commit is made.
# This is a basic configuration that ensures that each commit is properly formatted (using Black),
# does not have trailing whitespace, and passes Mypy and Flake8 checks.
# You can add or remove hooks as you like.
# See more details in https://pre-commit.com/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: .idea
      - id: trailing-whitespace
        exclude: .idea
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        exclude: .idea
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [ python ]
        args: [ ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: .idea
        additional_dependencies: [ flake8-bugbear ]
